# Generated by Django 5.2 on 2025-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik_number', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
    ]
